name: Diff

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  diff:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Build and run tests
        run: ./mvnw clean verify -B
